CC = g++
all: prog1 prog2 prog3 prog4 prog5

prog1: quesito1.cc 
	$(CC) -o $@ $<

prog2: quesito2.cc 
	$(CC) -o $@ $<

prog3: quesito3.cc 
	$(CC) -o $@ $<

prog4: quesito4.cc 
	$(CC) -o $@ $<

prog5: quesito5.cc
	$(CC) -o $@ $<

clean:
	rm -f prog1 prog2 prog3 prog4 prog5