all: prog1 prog2 prog3 prog4

prog1:: esercizio1.cc
	g++ -o prog1 esercizio1.cc

prog2:: esercizio2.cc
	g++ -o prog2 esercizio2.cc

prog3:: esercizio3.cc
	g++ -o prog3 esercizio3.cc

prog4:: esercizio4.cc
	g++ -o prog4 esercizio4.cc

clean: 
	rm - f prog1 prog2 prog3 prog4